version: "3.9"

volumes:
  payment_orchestrator_db:
  stripe_cli:
  payment-orchestrator:

services:

  payment-orchestrator:
    container_name: payment_orchestrator
    env_file:
      - .env
    build:
      context: ./services/payment-orchestrator
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL} 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8083:8083"
    depends_on:
      - payment_orchestrator_db
    restart: unless-stopped


  payment_orchestrator_db:
    image: postgres:18-alpine
    container_name: payment_orchestrator_db
    environment:
      POSTGRES_DB: payment_orchestrator_db
      POSTGRES_USER: payment_orchestrator
      POSTGRES_PASSWORD: payment_orchestrator
    volumes:
      - payment_orchestrator_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  stripe_cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    env_file:
      - .env
    command: >
      listen
      --api-key ${STRIPE_SECRET_KEY}
      --forward-to http://payment_orchestrator:8083/api/stripe-webhook
