version: "3.9"

volumes:
  auth_db:
  order_db:
  payment_orchestrator_db:
  stripe_cli:
  payment-orchestrator:

services:
  api-gateway:
    container_name: api_gateway
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=PhuongThanhDo_BiThuat_2026
      - AUTH_SERVICE_URL=http://auth:8081
      - ORDER_SERVICE_URL=http://order:8082
      - PAYMENT_SERVICE_URL=http://payment-orchestrator:8083
    restart: unless-stopped

  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:auth_password@auth_db:5432/auth_db
    environment:
      - PORT=8081
      - DATABASE_URL=postgres://postgres:auth_password@auth_db:5432/auth_db
      - JWT_SECRET=PhuongThanhDo_BiThuat_2026
    ports:
      - "8081:8081"
    depends_on:
      - auth_db
    restart: unless-stopped

  auth_db:
    image: postgres:18-alpine
    container_name: auth_db
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=auth_password
      - PGDATA=/var/lib/postgresql/data/pgdata 
    volumes:
      - auth_db:/var/lib/postgresql/data
    ports:
      - "5430:5432"
  
  order:
    container_name: order
    env_file:
      - .env
    build:
      context: ./services/order
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${ORDER_DB_URL}
    environment:
      - DATABASE_URL=${ORDER_DB_URL}
    ports:
      - "8082:8082"
    depends_on:
      - order_db
    restart: unless-stopped

  payment-orchestrator:
    container_name: payment_orchestrator
    env_file:
      - .env
    build:
      context: ./services/payment-orchestrator
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${PAYMENT_DB_URL} 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${PAYMENT_DB_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8083:8083"
    depends_on:
      - payment_orchestrator_db
    restart: unless-stopped

  order_db:
    image: postgres:18-alpine
    container_name: order_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=${ORDER_DB_USER}
      - POSTGRES_PASSWORD=${ORDER_DB_PASSWORD}
    volumes:
      - order_db:/var/lib/postgresql/data
    ports:
      - "5431:5431"


  payment_orchestrator_db:
    image: postgres:18-alpine
    container_name: payment_orchestrator_db
    environment:
      POSTGRES_DB: payment_orchestrator_db
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    volumes:
      - payment_orchestrator_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  stripe_cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    env_file:
      - .env
    command: >
      listen
      --api-key ${STRIPE_SECRET_KEY}
      --forward-to http://payment_orchestrator:8083/api/stripe-webhook
  
