version: "3.9"

volumes:
  order_db:
  payment_orchestrator_db:
  stripe_cli:
  payment-orchestrator:
  soft-hsm:
  kms_db:
  softhsm_tokens:
    driver: local

services:

  order:
    container_name: order
    env_file:
      - .env
    build:
      context: ./services/order
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${ORDER_DB_URL}
    environment:
      - DATABASE_URL=${ORDER_DB_URL}
    ports:
      - "8082:8082"
    depends_on:
      - order_db
    restart: unless-stopped

  payment-orchestrator:
    container_name: payment_orchestrator
    env_file:
      - .env
    build:
      context: ./services/payment-orchestrator
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${PAYMENT_DB_URL} 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${PAYMENT_DB_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8083:8083"
    depends_on:
      - payment_orchestrator_db
    restart: unless-stopped

  kms:
    container_name: kms
    env_file:
      - .env
    build: 
      context: ./services/kms
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${KMS_DB_URL} 
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${KMS_DB_URL}
      - USER_PIN=${HSM_USER_PIN}
      - TOKEN_LABEL=${HSM_TOKEN_LABEL}
    ports:
      - "8084:8084"
    volumes:
      - softhsm_tokens:/var/lib/softhsm/tokens
    depends_on:
      - kms_db
    restart: unless-stopped

  order_db:
    image: postgres:18-alpine
    container_name: order_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=${ORDER_DB_USER}
      - POSTGRES_PASSWORD=${ORDER_DB_PASSWORD}
    volumes:
      - order_db:/var/lib/postgresql/data
    ports:
      - "5431:5431"

  payment_orchestrator_db:
    image: postgres:18-alpine
    container_name: payment_orchestrator_db
    environment:
      POSTGRES_DB: payment_orchestrator_db
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    volumes:
      - payment_orchestrator_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kms_db:
    container_name: kms_db
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: kms_db
      POSTGRES_USER: ${KMS_DB_USER}
      POSTGRES_PASSWORD: ${KMS_DB_PASSWORD}
    volumes:
      - kms_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  stripe_cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    env_file:
      - .env
    command: >
      listen
      --api-key ${STRIPE_SECRET_KEY}
      --forward-to http://payment_orchestrator:8083/api/stripe-webhook

  soft-hsm:
    container_name: soft-hsm
    env_file:
      - .env
    build: 
      context: ./infra/softhsm
      dockerfile: Dockerfile
    environment:
      - HSM_SO_PIN=${HSM_SO_PIN}
      - HSM_USER_PIN=${HSM_USER_PIN}
    volumes:
      - softhsm_tokens:/var/lib/softhsm/tokens
    restart: unless-stopped


