directories.tokendir = /var/lib/softhsm/tokens/
 
# Cách lưu dữ liệu backend
objectstore.backend = file
 
# Log level: ERROR, WARNING, INFO, DEBUG
log.level = INFO
 
# PKCS#11 library path (used by Vault pkcs11 seal)
# Mount point: /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so